// Deterministic matching/ranking engine (architecture doc §9). The score is
// always computed here from structured features — never generated by a model.
// Every result carries a human-readable explanation of *why* it was ranked,
// per the spec: "Do not show an arbitrary black-box 97% match without
// explanation."

import type { Competition, Student } from "@sop/db";
import { parseJsonArray, parseJsonObject } from "./json";
import { checkEligibility, type EligibilityCheck } from "./eligibility";

// Product doc §18/§57: recommendation labels separate from eligibility.
// STARTER = good entry point; STRONG_MATCH = strong profile alignment;
// STRETCH = difficult but aligned and worth attempting. Deterministic rules
// only — no fake win-probability numbers.
export type MatchLabel = "STARTER" | "STRONG_MATCH" | "STRETCH";

const DIFFICULTY_RANK: Record<string, number> = {
  STARTER: 0,
  INTERMEDIATE: 1,
  COMPETITIVE: 2,
  ADVANCED: 2,
  HIGHLY_COMPETITIVE: 3,
};

export function matchLabel(breakdown: {
  score: number;
  verdict: EligibilityCheck["verdict"];
  difficulty: string | null | undefined;
}): MatchLabel {
  // Not eligible = a future/"not yet" pathway, never shown in the normal feed
  // (doc §62); surfaced as STRETCH so deliberate searches stay visible with
  // the explicit not-eligible explanation.
  if (breakdown.verdict === "NOT_ELIGIBLE") return "STRETCH";
  const difficulty = (breakdown.difficulty ?? "").toUpperCase();
  const rank = DIFFICULTY_RANK[difficulty] ?? 1;
  // Difficulty dominates: genuinely hard competitions are always stretch.
  if (rank >= 3) return "STRETCH";
  if (breakdown.score >= 65) return "STRONG_MATCH";
  if (rank <= 1 && breakdown.score >= 45) return "STARTER";
  if (breakdown.score >= 45) return "STRETCH"; // moderate difficulty + moderate fit
  return "STARTER";
}

export const MATCH_LABEL_DESCRIPTIONS: Record<MatchLabel, string> = {
  STARTER: "Good entry point — a reasonable place to begin.",
  STRONG_MATCH: "Strong alignment with your profile.",
  STRETCH: "Ambitious but aligned — worth preparing for.",
};

// Weighted, deterministic match score.
const WEIGHTS = {
  eligibility: 0.3,
  interest: 0.2,
  academicField: 0.15,
  skills: 0.1,
  location: 0.05,
  difficulty: 0.05,
  format: 0.05,
  deadline: 0.05,
  benefits: 0.05,
} as const;

export interface MatchBreakdown {
  score: number; // 0-100
  components: Record<keyof typeof WEIGHTS, number>; // each 0-1
  eligible: boolean;
  verdict: EligibilityCheck["verdict"];
  label: MatchLabel;
  explanations: string[];
  gaps: string[]; // preparation needs (doc §57 potential_gaps)
}

function overlapRatio(a: string[], b: string[]): number {
  if (a.length === 0 || b.length === 0) return 0;
  const setB = new Set(b.map((x) => x.toLowerCase()));
  const hits = a.filter((x) => setB.has(x.toLowerCase())).length;
  return Math.min(1, hits / Math.max(1, a.length));
}

function deadlineScore(deadline: Date | null): number {
  if (!deadline) return 0.5;
  const daysLeft = (deadline.getTime() - Date.now()) / (1000 * 60 * 60 * 24);
  if (daysLeft < 0) return 0;
  if (daysLeft < 3) return 0.5; // urgent but still actionable
  if (daysLeft > 120) return 0.6; // far off, lower urgency
  return 1;
}

function deadlineExplanation(deadline: Date | null): string | null {
  if (!deadline) return null;
  const daysLeft = Math.ceil((deadline.getTime() - Date.now()) / (1000 * 60 * 60 * 24));
  if (daysLeft < 0) return "Deadline has passed.";
  if (daysLeft <= 7) return `Deadline in ${daysLeft} day${daysLeft === 1 ? "" : "s"} — apply soon.`;
  if (daysLeft <= 60) return `Deadline in ${daysLeft} days — enough time to prepare.`;
  return null;
}

export function computeMatch(student: Student, competition: Competition): MatchBreakdown {
  const profileRules = parseJsonObject<{
    ageMin?: number | null;
    ageMax?: number | null;
    educationLevels?: string[] | null;
    countries?: string[] | null;
  }>(competition.eligibilityRules);

  const subject = {
    age: student.age,
    educationLevel: student.educationLevel,
    country: student.country,
  };

  const check = checkEligibility(subject, profileRules);

  const studentInterests = parseJsonArray(student.interests);
  const studentFields = parseJsonArray(student.fieldOfStudy);
  const studentSkills = parseJsonArray(student.skills);
  const studentFormats = parseJsonArray(student.preferredFormats);
  const competitionCategories = parseJsonArray(competition.category);
  const competitionBenefits = parseJsonArray(competition.benefits);
  const competitionCountries = parseJsonArray(competition.countries);

  const interest = overlapRatio(studentInterests, competitionCategories);
  const academicField = overlapRatio(studentFields, competitionCategories);
  const skills = overlapRatio(studentSkills, competitionCategories);

  const components: MatchBreakdown["components"] = {
    eligibility: check.verdict === "ELIGIBLE" ? 1 : 0,
    interest,
    academicField,
    skills,
    location:
      competitionCountries.length === 0 || competitionCountries.includes(student.country) ? 1 : 0,
    difficulty: competition.difficulty ? 0.6 : 0.3,
    format:
      studentFormats.length === 0 || studentFormats.includes(competition.format) ? 1 : 0.2,
    deadline: deadlineScore(competition.deadline),
    benefits: competitionBenefits.length > 0 ? 1 : 0.4,
  };

  const score =
    Object.entries(WEIGHTS).reduce(
      (sum, [key, weight]) => sum + weight * components[key as keyof typeof WEIGHTS],
      0
    ) * 100;

  // Human-readable explanations, strongest signals first.
  const explanations: string[] = [];
  if (check.verdict === "ELIGIBLE") explanations.push("You meet the recorded eligibility rules.");
  else if (check.verdict === "NOT_ELIGIBLE") explanations.push(...check.reasons);
  else explanations.push(...check.reasons);

  if (academicField > 0)
    explanations.push(
      `Field of study overlaps with this competition (${Math.round(academicField * 100)}% of your fields).`
    );
  if (interest > 0)
    explanations.push(`Matches ${Math.round(interest * 100)}% of your stated interests.`);
  if (skills > 0) explanations.push("Your skills align with the competition's focus areas.");
  const deadlineNote = deadlineExplanation(competition.deadline);
  if (deadlineNote) explanations.push(deadlineNote);
  if (components.format === 1 && studentFormats.length > 0)
    explanations.push(`Delivered ${competition.format.toLowerCase()}, which matches your preference.`);
  if (competitionBenefits.includes("cash_prize"))
    explanations.push("Offers a cash prize.");
  if (competitionBenefits.includes("certificate"))
    explanations.push("Offers a certificate.");
  if (competitionBenefits.includes("scholarship"))
    explanations.push("Offers a scholarship.");

  // Preparation gaps (doc §57): concrete, encouraging, never discouraging.
  const gaps: string[] = [];
  if (interest === 0 && academicField === 0)
    gaps.push("This is outside your recorded interests — worth exploring if curious.");
  if (skills === 0)
    gaps.push("You haven't listed related skills yet — preparation materials can help.");
  if (check.verdict === "UNCERTAIN")
    gaps.push("Some eligibility facts are missing from your profile — complete it to confirm.");
  const label = matchLabel({ score: Math.round(score), verdict: check.verdict, difficulty: competition.difficulty });
  if (label === "STRETCH" && check.verdict === "ELIGIBLE")
    explanations.push("This one is a challenge — the preparation pathway below can get you ready.");

  return {
    score: Math.round(score),
    components,
    eligible: check.verdict === "ELIGIBLE",
    verdict: check.verdict,
    label,
    explanations,
    gaps,
  };
}
